[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "The Development Experience Is Different With Rust"

[output.html]
additional-js = ["src/js/highlightjs-line-numbers.min.js"]
